import { readFileSync, writeFileSync } from 'node:fs';
const journal = JSON.parse(
  readFileSync('drizzle/meta/_journal.json', 'utf8'),
) as { entries: { idx: number; tag: string }[] };
if (
  !journal.entries.length ||
  journal.entries.some(
    (entry, index) => entry.idx !== index || !/^[a-zA-Z0-9_]+$/.test(entry.tag),
  )
)
  throw new Error('Invalid or empty Drizzle migration journal.');
const migrations = Object.fromEntries(
  journal.entries.map((entry) => [
    `m${String(entry.idx).padStart(4, '0')}`,
    readFileSync(`drizzle/${entry.tag}.sql`, 'utf8'),
  ]),
);
// Bundle generated SQL as string constants so Expo and Node tests use the exact
// same Drizzle journal without a runtime filesystem or a custom SQL loader.
writeFileSync(
  'src/data/migrations.ts',
  '// Generated by npm run db:generate. Do not edit.\nexport default ' +
    JSON.stringify({ journal, migrations }, null, 2) +
    ';\n',
);
